/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andrzej_MyComponent */

#ifndef _Included_com_andrzej_MyComponent
#define _Included_com_andrzej_MyComponent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_andrzej_MyJNIUtility */

#ifndef _Included_com_andrzej_MyJNIUtility
#define _Included_com_andrzej_MyJNIUtility
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andrzej_MyJNIUtility
 * Method:    getProcessWorkingSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_andrzej_MyJNIUtility_getProcessWorkingSet
  (JNIEnv *, jobject);

/*
 * Class:     com_andrzej_MyJNIUtility
 * Method:    getProcessVMSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_andrzej_MyJNIUtility_getProcessVMSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
